### ISSUE TITLE
Shock the Web / Update prizes component to include new 3Ds + Sats denomination

### ISSUE THREAD

**Issue by barefoot-88** [peakshift/bolt.fun#36]
**Update prize images**
Currently the prize images are medals. These needs to be changed to the following images:

![gold-2](https://user-images.githubusercontent.com/36778205/157441437-97444c8b-69b7-4608-8975-2856eb0ea7ed.png)
![silver](https://user-images.githubusercontent.com/36778205/157441070-62fe613b-5f1a-4161-a07a-fd684db32064.png)
![bronze](https://user-images.githubusercontent.com/36778205/157441128-a46a03f0-ed79-4772-952f-fe2aae3d3abb.png)

**Update prize denomination from USD to sats**
We will be giving teams their prizes in satoshis rather than USD, so this needs changing.
@johnsBeharry please could you convert these amounts and change them on the website!

Preview these design updates in Figma:
[Shock the Web](https://www.figma.com/file/SrwhugoFalEyB8TKhBMLIw/Shock-the-Web?node-id=382%3A635)

**Comment by johnsBeharry** [comment]
it's been added. looks 🔥
