### ISSUE TITLE
Update product details on makers.bolt.fun

### ISSUE THREAD

**Issue by barefoot-88** [peakshift/bolt.fun#37]
Update product details, including short descriptions and images for projects. You can find product details and screenshots here:

https://doc.clickup.com/d/h/hept5-2968/dac482d309a0ff8

New logo
- Geyser

![geyser](https://user-images.githubusercontent.com/36778205/157433567-4b1e41db-23d4-4a80-b48f-ee248ee87f1e.jpg)

**Comment by MTG2000** [comment]
the backend api is still not returning the description & screenshots
they should be inserted at the data-base there before I am able to make use of them
